### ISSUE TITLE
F-3 Al pulsar casos >> listado >> nuevo genera error en rol administrador y coordinador de oficina

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#137]
![Captura de pantalla de 2020-12-31 07-35-47](https://user-images.githubusercontent.com/10052756/103410814-0b51dc80-4b3b-11eb-80c2-f5b84a13497e.png)

**Comment by vtamara** [comment]
Resuelto

**Comment by vtamara** [comment]
Gracias.
