### ISSUE TITLE
F-5 Al editar una actividad genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#139]
![Captura de pantalla de 2020-12-31 07-49-44](https://user-images.githubusercontent.com/10052756/103411220-d5155c80-4b3c-11eb-9298-ae469115a185.png)

**Comment by vtamara** [comment]
Gracias. Resuelto

**Comment by vtamara** [comment]
Gracias. Resuelto
