### ISSUE TITLE
F-9 Al pulsar en Actividades >> convenios financiados >> Nuevo genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#143]
![Captura de pantalla de 2020-12-31 08-11-06](https://user-images.githubusercontent.com/10052756/103411824-03486b80-4b40-11eb-90b9-ebf5e4da9d70.png)

**Comment by vtamara** [comment]
Gracias. Resuelto
