### ISSUE TITLE
F-151 Mapa no filtra por departamento ni presunto responsable [1]

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#151]
![Captura de pantalla de 2021-01-09 15-35-45](https://user-images.githubusercontent.com/10052756/104108287-479ae080-5291-11eb-8a6b-4af6aa2deb9a.png)

**Comment by vtamara** [comment]
Se resolvió la alerta. Pero no está filtrando por Departamento ni Presunto Responsable.

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/sivel2_sjrcol/pull/221 y https://github.com/pasosdeJesus/sivel2_sjr/pull/37  aunque aún falta elaborar lo que contendrá el mapa.  Sitios de salida de migraciones y desplazamientos?
[opera-mapa.pdf](https://github.com/pasosdeJesus/sivel2_sjrcol/files/6045672/opera-mapa.pdf)
