### ISSUE TITLE
F-156 Al crear un nuevo registro de tablas básicas, un nuevo registro de usuario, no aparece nueva (nombre de la tabla o usuario) sino aparece% {model}

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#156]
![Captura de pantalla de 2021-01-11 17-13-18](https://user-images.githubusercontent.com/10052756/104244414-58358d00-5430-11eb-989b-917bde219012.png)

**Comment by vtamara** [comment]
Resuelto
