### ISSUE TITLE
R-164 Hacer una plantilla que exporte toda la información de convenios financiados y posibilitar generación de campos que faltan.  Faltan: equipo de trabajo (todos los nombres concatenadso),  área, objetivos de marco lógico concatenados, primer y segundo objetivo de marco lógico (por separado código y texto); indicadores de objetivo concatenados, 4 primeros indicadores de objetivo por separado ref. objetivo, código, nombre, tipo; resultados concatenados, 4 primeros resultados de cada uno por separado ref obj. código, resultado; indicadores de resultado concatenados, 6 primeros indicadores de resultado y de cada uno por separado ref res, código, indicador, tipo; actividades de marco lógico concatenadas, 8 primeras actividades de marco lógico y de cada una por separado ref resultado, código, tipo, actividad, descripción, indicadores gifmm concatendados.  [6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_sjrcol#164]

**Comment by vtamara** [comment]
Crear la plantillahcm con id 45
La migración que cree esa plantilla que ejecute:
SELECT setval('public.heb412_gen_campoplantillahcm_id_seq', 5000);

Los campos de esta plantilla ponerlos a partir del id 2000.

**Comment by vtamara** [comment]
Avances con #177 y #178

**Comment by alejocruzrcc** [comment]
Desarrollo de la exportación de Casos:
1. Se creó una plantilla con el formato de exportación en ods par usar en la exportación, se adecuaron los campos y se diferenciaron por colores, finalmente se subió a nube-> plantillas y quedó  guardada en la carpeta public.[se implemento en 1 hora]
2. Se creó una Migración que al correrla se crean en la base de datos un nuveo registro para plantillahcm con la ruta listado extracompleto de convenios financiados. esta migración crea cada campo con el nombre generado del campo de la plantilla ods, y la posición en la hoja de cálculo, se hicieron validaciones para no generar conflictos con identificadores y se implementaron métodos para que los campos se generaran más rápidamente.  [se implementó en 5 horas]
3. Se realizó la exportación de cada Campo de la plantilla tal cual como lo plantea el requerimiento, se usaron identificiadores de patrones para ahorrar código, se realizaron validaciones para un solo convenio financiado, para varios, para cuando solo son algunos campos y otros no y para cuando no existe el campo.  [Se implementó en 5 horas]
 Cabe resaltar que  fue mal calculado el tiempo de desarrollo.

**Comment by vtamara** [comment]
- [] Aparecen intercambiados orden de columnas tipo de indicador y nombre en indicadores de resultado:
![orden-nombre-tipo-indicador-de-resultado](https://user-images.githubusercontent.com/701221/105096420-0961a600-5a75-11eb-94e3-238c7fed7ce0.png)

**Comment by vtamara** [comment]
Terminado con #182
