### ISSUE TITLE
F-214 Al generar un Consentimiento de Tratamiento de Datos en el resumen de un caso genera error 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#214]
![Captura de pantalla de 2021-02-18 12-03-46](https://user-images.githubusercontent.com/10052756/108393388-98332100-71e1-11eb-92cc-e1965d3c808a.png)

**Comment by vtamara** [comment]
Resulto con https://github.com/pasosdeJesus/sivel2_gen/commit/8cd425a56b61f2f7f434d43b6bd4d67105a97f3a
