### ISSUE TITLE
F-223 En filtro de actividades, primero filtramos convenio bien, pero al filtrar una actividad de marco lógico se borra. [0,6]

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#223]
![Captura de pantalla de 2021-02-25 12-02-48](https://user-images.githubusercontent.com/10052756/109188917-6c73e600-7761-11eb-8edf-bc1f33d1e1f9.png)

**Comment by vtamara** [comment]
Confirmado
https://user-images.githubusercontent.com/701221/109341411-6270e680-7838-11eb-98cc-aea99e1464a3.mp4
