### ISSUE TITLE
F-257 Al guardar un caso genera error con administrador 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#257]

**Comment by vtamara** [comment]
![screencapture-colombia-sjrlac-info-5100-casos-1166-2021-03-19-13_04_36](https://user-images.githubusercontent.com/701221/111816851-51e9e400-88ab-11eb-823d-ba20c18fff6a.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-19 13-48-50](https://user-images.githubusercontent.com/10052756/111852239-2cc59780-88e4-11eb-8bd2-28c7975872d4.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-19 19-59-27](https://user-images.githubusercontent.com/10052756/111854578-dbbaa100-88ed-11eb-9451-fc73bce8bc6e.png)
![Captura de pantalla de 2021-03-19 20-03-20](https://user-images.githubusercontent.com/10052756/111854642-39e78400-88ee-11eb-88c1-203ffd426ebd.png)

**Comment by vtamara** [comment]
Resuelto con #261
