### ISSUE TITLE
F-258 En un convenio, al borrar una actividad del marco lógico 243 en sitio de pruebas y guardar  genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#258]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-21 18-19-50](https://user-images.githubusercontent.com/10052756/111924467-be630f80-8a72-11eb-88c7-36cc12d56b8d.png)

**Comment by vtamara** [comment]
Resuelto con: https://github.com/pasosdeJesus/sivel2_sjrcol/commit/c29ef66aefcf72de374db8e98757599a07be0c5a
