### ISSUE TITLE
F-260 En mapa al filtrar por categoría de violencia aparece una alerta con un mensaje de error.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#260]
![Captura de pantalla de 2021-03-21 20-10-05](https://user-images.githubusercontent.com/10052756/111928521-e3ab4a00-8a81-11eb-8dbb-312612a2c17c.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/sivel2_sjr/commit/c699c2858397e79e9fed1a37efba3ebf21b7996b

**Comment by vtamara** [comment]
Esperando cambio de título
