### ISSUE TITLE
F-262 Al generar el conteo vacíos de protección genera error  

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#262]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-22 21-18-48](https://user-images.githubusercontent.com/10052756/112083251-b1b6e800-8b54-11eb-8fe3-00763c468fab.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/sivel2_sjrcol/commit/f0c32476c48221bab2fba9a4d31010325f45ee5c
