### ISSUE TITLE
F-263 Al eliminar actividad 872 en sitio de pruebas genera error, pero si la borro.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#263]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-23 09-13-23](https://user-images.githubusercontent.com/10052756/112160659-5f0f1780-8bb8-11eb-9e37-037f4d5ce77a.png)

**Comment by vtamara** [comment]
No se ha logrado reproducir.   ¿Bajo que condiciones ocurre?
