### ISSUE TITLE
F-276  En casos >> Migración no se puede elegir departamento de llegada

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#276]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-28 14-18-50](https://user-images.githubusercontent.com/10052756/112765124-514efd00-8fd1-11eb-9a7d-60dbbef45d8c.png)

**Comment by vtamara** [comment]
Resuelto en nuevo control
