### ISSUE TITLE
F-277 En caso >> Anexos se sube un anexo y genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#277]
![Captura de pantalla de 2021-03-28 14-30-31](https://user-images.githubusercontent.com/10052756/112765431-cff86a00-8fd2-11eb-98bc-7fb131353e3a.png)

**Comment by vtamara** [comment]
No reproducible.
Se probó:
* anexar a un contacto.
* Anexar a un integrante del núcleo familair
* anexar por pestaña anexos
