### ISSUE TITLE
F-279 Al editar caso 1159 en sitio de desarrollo, borrar Núcleo familiar y guardar genera error 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#279]

**Comment by vtamara** [comment]
Pensamos que se relacionaba con actos con desplazamiento.  Se prueba como solución 
https://github.com/pasosdeJesus/sivel2_sjrcol/commit/601e90b91c05eb80691458e92619a674ae2e578e
