### ISSUE TITLE
F-316 No se puede generar un reporte genérico de casos genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#316]
![Captura de pantalla de 2021-04-17 11-55-00](https://user-images.githubusercontent.com/10052756/115120616-098a1880-9f74-11eb-8bf6-6f0fe8adfb7a.png)

**Comment by vtamara** [comment]
Se retiro ese tipo de reporte que no estaba configurado.
