### ISSUE TITLE
F-320 En casos >> migración >> salida se puede elegir país, pero no permite elegir departamento 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#320]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-04-22 10-01-53](https://user-images.githubusercontent.com/10052756/115738088-542fda00-a352-11eb-97b6-4179b2ab4ae5.png)

**Comment by vtamara** [comment]
No reproducible.
