### ISSUE TITLE
F-328 Al filtrar por sexo en  Conteo de beneficiarios por actividad de convenio  genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#328]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-04-23 11-32-03](https://user-images.githubusercontent.com/10052756/115902124-b1498f80-a427-11eb-8ef4-b030bcb87e01.png)

**Comment by vtamara** [comment]
Solucioado entre otras con https://github.com/pasosdeJesus/cor1440_gen/commit/8a390767e91dcae1ee4d6f17412d3de307680dae
