### ISSUE TITLE
F-336 Al generar listado extracompleto de casos genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#336]

**Comment by vtamara** [comment]
Resuelto.

**Comment by BlancaInesAcosta** [comment]
P-U-F-336  Probar  F-336, F-326, F-350, F-323, F-316, F-328, F-325, R-337, R-338, R-339, R-353, R-351, R-295, R-305  [1.6]
