### ISSUE TITLE
F-337 Al pulsar conteos >> personas atendidas genera error [1,5]

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#337]
![Captura de pantalla de 2021-04-29 13-46-53](https://user-images.githubusercontent.com/10052756/116602560-82349180-a8f1-11eb-8db0-5c8d0187cea3.png)

**Comment by alejocruzrcc** [comment]
Tiempo: 1.5 Horas

**Comment by vtamara** [comment]
Iniciado con https://github.com/pasosdeJesus/sivel2_sjrcol/pull/352

**Comment by vtamara** [comment]
![Action Controller- Exception caught 5-5-2021 5-34-20 a- m-](https://user-images.githubusercontent.com/701221/117128864-94845480-ad63-11eb-8f08-66da3c054264.png)

**Comment by vtamara** [comment]
Completado con https://github.com/pasosdeJesus/sivel2_sjrcol/pull/354
