### ISSUE TITLE
F-338 Al pulsar conteos >> municipios expulsores/receptores

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#338]
![Captura de pantalla de 2021-04-29 13-50-11](https://user-images.githubusercontent.com/10052756/116602886-e6efec00-a8f1-11eb-8bee-e19d82539d44.png)

**Comment by alejocruzrcc** [comment]
tiempo: 0.5 horas

**Comment by vtamara** [comment]
Implementado con https://github.com/pasosdeJesus/sivel2_sjrcol/pull/352
