### ISSUE TITLE
F-340 En Reporte actividad con caso hay 2 formatos para generar listados: Reporte de tipos de atención por casos y actividades y  listado de casos y actividades pero se genera la plantilla vacía

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_sjrcol#340]
![Captura de pantalla de 2021-04-29 14-44-45](https://user-images.githubusercontent.com/10052756/116609039-82388f80-a8f9-11eb-8d62-a0f1d8f53d41.png)

**Comment by vtamara** [comment]
En sitio de desarrollo se dejó uno sólo y se configuró como está en sitio de producción.
