### ISSUE TITLE
R-341 Mejorar R-322, que al crear un nuevo presunto responsable quede elegido en el campo donde se crea y que el dialogo tenga el estilo de creación de registros en tabla básica [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_sjrcol#342]

**Comment by vtamara** [comment]
https://github.com/pasosdeJesus/sivel2_sjrcol/pull/344/files

**Comment by vtamara** [comment]
![SI-JRSCOL 2-0b10 1-5-2021 4-38-13 a- m-](https://user-images.githubusercontent.com/701221/116776578-ad70cb00-aa2e-11eb-9a4c-84ac09856f57.png)

**Comment by BlancaInesAcosta** [comment]
P-U-R-341  Probar  R-341, R-306, R-333, R-333, R-332, R-349, R-350, F-313  [1]
